### ISSUE TITLE
Symlinks are resolved even when `followSymlinks` is `false`

### ISSUE THREAD

**Issue by TimBeyer** [thenativeweb/walk-file-tree#175]
I was using the library to walk a project which contains some test cases.
Among those test cases is a symlink that points to a file that does not exist.
Currently the library crashes since it cannot stat the path it points to since it is invalid specifically to test for that.
Ideally either `followSymlinks` would immediately skip anything that's a symlink, or there should be an option that ignores not just symlinked directories but also files.

**Comment by goloroden** [comment]
Thanks for bringing up this issue.

Since we do not maintain this library any more, please fork it, and adjust the code as needed.
